2024-01-30 11:54:00,598:openFile:Corrupt file
Traceback (most recent call last):
  File "C:\Users\ananya.bhat\PythonPractice\ExceptionHandlingEg\handleExceptions.py", line 9, in openFile
    raise Exception
Exception
2024-01-30 11:54:00,603:openFile:Finally block
